// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {type Infer as __Infer} from "spacetimedb";

// Import all procedure arg schemas
import * as CreateSharedFiltersProcedure from "../create_shared_filters_procedure";
import * as ReadSharedFiltersProcedure from "../read_shared_filters_procedure";

export type CreateSharedFiltersArgs = __Infer<typeof CreateSharedFiltersProcedure.params>;
export type CreateSharedFiltersResult = __Infer<typeof CreateSharedFiltersProcedure.returnType>;
export type ReadSharedFiltersArgs = __Infer<typeof ReadSharedFiltersProcedure.params>;
export type ReadSharedFiltersResult = __Infer<typeof ReadSharedFiltersProcedure.returnType>;

