// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {type Infer as __Infer} from "spacetimedb";

// Import all reducer arg schemas
import AssignCraftBountyReducer from "../assign_craft_bounty_reducer";
import BeginIntegrationLinkForExternalReducer from "../begin_integration_link_for_external_reducer";
import BeginIntegrationLinkReducer from "../begin_integration_link_reducer";
import ClaimIntegrationLinkReducer from "../claim_integration_link_reducer";
import ClearCraftBountyReducer from "../clear_craft_bounty_reducer";
import DeleteBountyRuleReducer from "../delete_bounty_rule_reducer";
import DeleteCraftBountyOverrideReducer from "../delete_craft_bounty_override_reducer";
import DeleteCraftFilterWatchReducer from "../delete_craft_filter_watch_reducer";
import DeleteLoyaltyBonusTotalReducer from "../delete_loyalty_bonus_total_reducer";
import DeleteLoyaltyRewardReducer from "../delete_loyalty_reward_reducer";
import DeleteLoyaltyRuleReducer from "../delete_loyalty_rule_reducer";
import DeleteNotificationReducer from "../delete_notification_reducer";
import DeleteSavedCraftFilterReducer from "../delete_saved_craft_filter_reducer";
import EnsureAccountReducer from "../ensure_account_reducer";
import ImportHistoricalBountyLedgerReducer from "../import_historical_bounty_ledger_reducer";
import LinkDiscordViaSpacetimeAuthReducer from "../link_discord_via_spacetime_auth_reducer";
import LinkIntegrationReducer from "../link_integration_reducer";
import MarkAllNotificationsReadReducer from "../mark_all_notifications_read_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import NoteIntegrationLinkExternalReducer from "../note_integration_link_external_reducer";
import PostCraftNotificationReducer from "../post_craft_notification_reducer";
import RecordBountyPaymentReducer from "../record_bounty_payment_reducer";
import RegisterServicePrincipalReducer from "../register_service_principal_reducer";
import ReorderBountyRulesReducer from "../reorder_bounty_rules_reducer";
import RevokeServicePrincipalReducer from "../revoke_service_principal_reducer";
import SeedCraftBountyEntitlementReducer from "../seed_craft_bounty_entitlement_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import UnlinkIntegrationReducer from "../unlink_integration_reducer";
import UpsertBountyRuleReducer from "../upsert_bounty_rule_reducer";
import UpsertCraftBountyEntitlementReducer from "../upsert_craft_bounty_entitlement_reducer";
import UpsertCraftBountyOverrideReducer from "../upsert_craft_bounty_override_reducer";
import UpsertCraftFilterWatchReducer from "../upsert_craft_filter_watch_reducer";
import UpsertLoyaltyBonusTotalReducer from "../upsert_loyalty_bonus_total_reducer";
import UpsertLoyaltyRewardReducer from "../upsert_loyalty_reward_reducer";
import UpsertLoyaltyRuleReducer from "../upsert_loyalty_rule_reducer";
import UpsertSavedCraftFilterReducer from "../upsert_saved_craft_filter_reducer";

export type AssignCraftBountyParams = __Infer<typeof AssignCraftBountyReducer>;
export type BeginIntegrationLinkParams = __Infer<typeof BeginIntegrationLinkReducer>;
export type BeginIntegrationLinkForExternalParams = __Infer<typeof BeginIntegrationLinkForExternalReducer>;
export type ClaimIntegrationLinkParams = __Infer<typeof ClaimIntegrationLinkReducer>;
export type ClearCraftBountyParams = __Infer<typeof ClearCraftBountyReducer>;
export type DeleteBountyRuleParams = __Infer<typeof DeleteBountyRuleReducer>;
export type DeleteCraftBountyOverrideParams = __Infer<typeof DeleteCraftBountyOverrideReducer>;
export type DeleteCraftFilterWatchParams = __Infer<typeof DeleteCraftFilterWatchReducer>;
export type DeleteLoyaltyBonusTotalParams = __Infer<typeof DeleteLoyaltyBonusTotalReducer>;
export type DeleteLoyaltyRewardParams = __Infer<typeof DeleteLoyaltyRewardReducer>;
export type DeleteLoyaltyRuleParams = __Infer<typeof DeleteLoyaltyRuleReducer>;
export type DeleteNotificationParams = __Infer<typeof DeleteNotificationReducer>;
export type DeleteSavedCraftFilterParams = __Infer<typeof DeleteSavedCraftFilterReducer>;
export type EnsureAccountParams = __Infer<typeof EnsureAccountReducer>;
export type ImportHistoricalBountyLedgerParams = __Infer<typeof ImportHistoricalBountyLedgerReducer>;
export type LinkDiscordViaSpacetimeAuthParams = __Infer<typeof LinkDiscordViaSpacetimeAuthReducer>;
export type LinkIntegrationParams = __Infer<typeof LinkIntegrationReducer>;
export type MarkAllNotificationsReadParams = __Infer<typeof MarkAllNotificationsReadReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type NoteIntegrationLinkExternalParams = __Infer<typeof NoteIntegrationLinkExternalReducer>;
export type PostCraftNotificationParams = __Infer<typeof PostCraftNotificationReducer>;
export type RecordBountyPaymentParams = __Infer<typeof RecordBountyPaymentReducer>;
export type RegisterServicePrincipalParams = __Infer<typeof RegisterServicePrincipalReducer>;
export type ReorderBountyRulesParams = __Infer<typeof ReorderBountyRulesReducer>;
export type RevokeServicePrincipalParams = __Infer<typeof RevokeServicePrincipalReducer>;
export type SeedCraftBountyEntitlementParams = __Infer<typeof SeedCraftBountyEntitlementReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type UnlinkIntegrationParams = __Infer<typeof UnlinkIntegrationReducer>;
export type UpsertBountyRuleParams = __Infer<typeof UpsertBountyRuleReducer>;
export type UpsertCraftBountyEntitlementParams = __Infer<typeof UpsertCraftBountyEntitlementReducer>;
export type UpsertCraftBountyOverrideParams = __Infer<typeof UpsertCraftBountyOverrideReducer>;
export type UpsertCraftFilterWatchParams = __Infer<typeof UpsertCraftFilterWatchReducer>;
export type UpsertLoyaltyBonusTotalParams = __Infer<typeof UpsertLoyaltyBonusTotalReducer>;
export type UpsertLoyaltyRewardParams = __Infer<typeof UpsertLoyaltyRewardReducer>;
export type UpsertLoyaltyRuleParams = __Infer<typeof UpsertLoyaltyRuleReducer>;
export type UpsertSavedCraftFilterParams = __Infer<typeof UpsertSavedCraftFilterReducer>;

