// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  regionId: __t.u8().name("region_id"),
  supplies: __t.i32(),
  numTiles: __t.u32().name("num_tiles"),
  numTileNeighbors: __t.u32().name("num_tile_neighbors"),
  buildingMaintenance: __t.f32().name("building_maintenance"),
});
