// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  regionId: __t.u8().name("region_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  playerEntityId: __t.u64().name("player_entity_id"),
  build: __t.bool(),
  inventory: __t.bool(),
  officer: __t.bool(),
  coOwner: __t.bool().name("co_owner"),
  owner: __t.bool(),
});
