// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";
import {CraftStatus,} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  ownerEntityId: __t.u64().name("owner_entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  buildingEntityId: __t.u64().name("building_entity_id"),
  firstSeen: __t.timestamp().name("first_seen"),
  recipeId: __t.i32().name("recipe_id"),
  count: __t.i32(),
  regionId: __t.u8().name("region_id"),
  public: __t.bool(),
  get status() {
    return CraftStatus;
  },
});
