// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  craftId: __t.u64().name("craft_id"),
  playerId: __t.u64().name("player_id"),
  contribution: __t.i32(),
});
