// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.9.0 (commit 9e0d92412ff2248f401a8ad12d535f2b5ac30912).

/* eslint-disable */
/* tslint:disable */
import {
    DbConnectionBuilder as __DbConnectionBuilder,
    type DbConnectionConfig as __DbConnectionConfig,
    DbConnectionImpl as __DbConnectionImpl,
    type ErrorContextInterface as __ErrorContextInterface,
    type EventContextInterface as __EventContextInterface,
    makeQueryBuilder as __makeQueryBuilder,
    procedures as __procedures,
    type QueryBuilder as __QueryBuilder,
    type ReducerEventContextInterface as __ReducerEventContextInterface,
    reducers as __reducers,
    type RemoteModule as __RemoteModule,
    schema as __schema,
    SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
    type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
    type SubscriptionHandleImpl as __SubscriptionHandleImpl,
    table as __table,
} from "spacetimedb";

// Import all reducer arg schemas
// Import all procedure arg schemas
// Import all table schema definitions
import ClaimInfoRow from "./claim_info_table";
import ClaimMemberRow from "./claim_member_table";
import ClaimMetaRow from "./claim_meta_table";
import ClaimSupplyRow from "./claim_supply_table";
import CraftContributionRow from "./craft_contribution_table";
import CraftMetaRow from "./craft_meta_table";
import CraftProgressRow from "./craft_progress_table";
import EnemyLocationRow from "./enemy_location_table";
import GrowthTimersRow from "./growth_timers_table";
import HerdLocationRow from "./herd_location_table";
import PlayerLocationRow from "./player_location_table";
import PlayerStateRow from "./player_state_table";
import RecipeMetaRow from "./recipe_meta_table";
import RegionRow from "./region_table";
import ResourceLocationRow from "./resource_location_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  claimInfo: __table({
    name: 'claim_info',
    indexes: [
      { accessor: 'entity_id', name: 'claim_info_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'claim_info_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'claim_info_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ClaimInfoRow),
  claimMember: __table({
    name: 'claim_member',
    indexes: [
      { accessor: 'by_claim', name: 'claim_member_claim_entity_id_idx_btree', algorithm: 'btree', columns: [
        'claimEntityId',
      ] },
      { accessor: 'entity_id', name: 'claim_member_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_player', name: 'claim_member_player_entity_id_idx_btree', algorithm: 'btree', columns: [
        'playerEntityId',
      ] },
      { accessor: 'by_region', name: 'claim_member_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'claim_member_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ClaimMemberRow),
  claimMeta: __table({
    name: 'claim_meta',
    indexes: [
      { accessor: 'by_building', name: 'claim_meta_building_desc_id_idx_btree', algorithm: 'btree', columns: [
        'buildingDescId',
      ] },
      { accessor: 'entity_id', name: 'claim_meta_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'claim_meta_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'claim_meta_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ClaimMetaRow),
  claimSupply: __table({
    name: 'claim_supply',
    indexes: [
      { accessor: 'entity_id', name: 'claim_supply_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'claim_supply_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'claim_supply_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ClaimSupplyRow),
  craftContribution: __table({
    name: 'craft_contribution',
    indexes: [
      { accessor: 'by_craft', name: 'craft_contribution_craft_id_idx_btree', algorithm: 'btree', columns: [
        'craftId',
      ] },
      { accessor: 'by_craft_and_player', name: 'craft_contribution_craft_id_player_id_idx_hash', algorithm: 'btree', columns: [
        'craftId',
        'playerId',
      ] },
      { accessor: 'id', name: 'craft_contribution_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'craft_contribution_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CraftContributionRow),
  craftMeta: __table({
    name: 'craft_meta',
    indexes: [
      { accessor: 'by_claim', name: 'craft_meta_claim_entity_id_idx_btree', algorithm: 'btree', columns: [
        'claimEntityId',
      ] },
      { accessor: 'entity_id', name: 'craft_meta_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_owner_and_claim', name: 'craft_meta_owner_entity_id_claim_entity_id_idx_btree', algorithm: 'btree', columns: [
        'ownerEntityId',
        'claimEntityId',
      ] },
      { accessor: 'by_owner', name: 'craft_meta_owner_entity_id_idx_btree', algorithm: 'btree', columns: [
        'ownerEntityId',
      ] },
    ],
    constraints: [
      { name: 'craft_meta_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CraftMetaRow),
  craftProgress: __table({
    name: 'craft_progress',
    indexes: [
      { accessor: 'entity_id', name: 'craft_progress_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'craft_progress_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CraftProgressRow),
  enemyLocation: __table({
    name: 'enemy_location',
    indexes: [
      { accessor: 'by_enemy_type', name: 'enemy_location_enemy_type_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
      ] },
      { accessor: 'by_enemy_type_and_region', name: 'enemy_location_enemy_type_region_id_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
        'regionId',
      ] },
      { accessor: 'entity_id', name: 'enemy_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'enemy_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'enemy_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EnemyLocationRow),
  growthTimers: __table({
    name: 'growth_timers',
    indexes: [
      { accessor: 'entity_id', name: 'growth_timers_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'growth_timers_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'growth_timers_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, GrowthTimersRow),
  herdLocation: __table({
    name: 'herd_location',
    indexes: [
      { accessor: 'by_enemy_type', name: 'herd_location_enemy_type_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
      ] },
      { accessor: 'by_enemy_type_and_region', name: 'herd_location_enemy_type_region_id_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
        'regionId',
      ] },
      { accessor: 'entity_id', name: 'herd_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'herd_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'herd_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, HerdLocationRow),
  playerLocation: __table({
    name: 'player_location',
    indexes: [
      { accessor: 'entity_id', name: 'player_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'player_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'player_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerLocationRow),
  playerState: __table({
    name: 'player_state',
    indexes: [
      { accessor: 'entity_id', name: 'player_state_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'player_state_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'player_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerStateRow),
  recipeMeta: __table({
    name: 'recipe_meta',
    indexes: [
      { accessor: 'id', name: 'recipe_meta_id_idx_hash', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'recipe_meta_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RecipeMetaRow),
  region: __table({
    name: 'region',
    indexes: [
      { accessor: 'id', name: 'region_id_idx_direct', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'region_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RegionRow),
  resourceLocation: __table({
    name: 'resource_location',
    indexes: [
      { accessor: 'entity_id', name: 'resource_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'resource_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { accessor: 'by_resource', name: 'resource_location_resource_id_idx_btree', algorithm: 'btree', columns: [
        'resourceId',
      ] },
      { accessor: 'by_resource_and_region', name: 'resource_location_resource_id_region_id_idx_btree', algorithm: 'btree', columns: [
        'resourceId',
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'resource_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ResourceLocationRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `claimInfo` instead. This alias will be removed in the next major version. */
    readonly "claim_info": Omit<typeof tablesSchema.schemaType.tables["claimInfo"], "accessorName"> & { readonly accessorName: "claim_info" };
    /** @deprecated Use `claimMember` instead. This alias will be removed in the next major version. */
    readonly "claim_member": Omit<typeof tablesSchema.schemaType.tables["claimMember"], "accessorName"> & { readonly accessorName: "claim_member" };
    /** @deprecated Use `claimMeta` instead. This alias will be removed in the next major version. */
    readonly "claim_meta": Omit<typeof tablesSchema.schemaType.tables["claimMeta"], "accessorName"> & { readonly accessorName: "claim_meta" };
    /** @deprecated Use `claimSupply` instead. This alias will be removed in the next major version. */
    readonly "claim_supply": Omit<typeof tablesSchema.schemaType.tables["claimSupply"], "accessorName"> & { readonly accessorName: "claim_supply" };
    /** @deprecated Use `craftContribution` instead. This alias will be removed in the next major version. */
    readonly "craft_contribution": Omit<typeof tablesSchema.schemaType.tables["craftContribution"], "accessorName"> & { readonly accessorName: "craft_contribution" };
    /** @deprecated Use `craftMeta` instead. This alias will be removed in the next major version. */
    readonly "craft_meta": Omit<typeof tablesSchema.schemaType.tables["craftMeta"], "accessorName"> & { readonly accessorName: "craft_meta" };
    /** @deprecated Use `craftProgress` instead. This alias will be removed in the next major version. */
    readonly "craft_progress": Omit<typeof tablesSchema.schemaType.tables["craftProgress"], "accessorName"> & { readonly accessorName: "craft_progress" };
    /** @deprecated Use `enemyLocation` instead. This alias will be removed in the next major version. */
    readonly "enemy_location": Omit<typeof tablesSchema.schemaType.tables["enemyLocation"], "accessorName"> & { readonly accessorName: "enemy_location" };
    /** @deprecated Use `growthTimers` instead. This alias will be removed in the next major version. */
    readonly "growth_timers": Omit<typeof tablesSchema.schemaType.tables["growthTimers"], "accessorName"> & { readonly accessorName: "growth_timers" };
    /** @deprecated Use `herdLocation` instead. This alias will be removed in the next major version. */
    readonly "herd_location": Omit<typeof tablesSchema.schemaType.tables["herdLocation"], "accessorName"> & { readonly accessorName: "herd_location" };
    /** @deprecated Use `playerLocation` instead. This alias will be removed in the next major version. */
    readonly "player_location": Omit<typeof tablesSchema.schemaType.tables["playerLocation"], "accessorName"> & { readonly accessorName: "player_location" };
    /** @deprecated Use `playerState` instead. This alias will be removed in the next major version. */
    readonly "player_state": Omit<typeof tablesSchema.schemaType.tables["playerState"], "accessorName"> & { readonly accessorName: "player_state" };
    /** @deprecated Use `recipeMeta` instead. This alias will be removed in the next major version. */
    readonly "recipe_meta": Omit<typeof tablesSchema.schemaType.tables["recipeMeta"], "accessorName"> & { readonly accessorName: "recipe_meta" };
    /** @deprecated Use `resourceLocation` instead. This alias will be removed in the next major version. */
    readonly "resource_location": Omit<typeof tablesSchema.schemaType.tables["resourceLocation"], "accessorName"> & { readonly accessorName: "resource_location" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.9.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "claim_info": "claimInfo",
  "claim_member": "claimMember",
  "claim_meta": "claimMeta",
  "claim_supply": "claimSupply",
  "craft_contribution": "craftContribution",
  "craft_meta": "craftMeta",
  "craft_progress": "craftProgress",
  "enemy_location": "enemyLocation",
  "growth_timers": "growthTimers",
  "herd_location": "herdLocation",
  "player_location": "playerLocation",
  "player_state": "playerState",
  "recipe_meta": "recipeMeta",
  "resource_location": "resourceLocation",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `claimInfo` instead. This alias will be removed in the next major version. */
  readonly "claim_info": __DbViewBase["claimInfo"];
  /** @deprecated Use `claimMember` instead. This alias will be removed in the next major version. */
  readonly "claim_member": __DbViewBase["claimMember"];
  /** @deprecated Use `claimMeta` instead. This alias will be removed in the next major version. */
  readonly "claim_meta": __DbViewBase["claimMeta"];
  /** @deprecated Use `claimSupply` instead. This alias will be removed in the next major version. */
  readonly "claim_supply": __DbViewBase["claimSupply"];
  /** @deprecated Use `craftContribution` instead. This alias will be removed in the next major version. */
  readonly "craft_contribution": __DbViewBase["craftContribution"];
  /** @deprecated Use `craftMeta` instead. This alias will be removed in the next major version. */
  readonly "craft_meta": __DbViewBase["craftMeta"];
  /** @deprecated Use `craftProgress` instead. This alias will be removed in the next major version. */
  readonly "craft_progress": __DbViewBase["craftProgress"];
  /** @deprecated Use `enemyLocation` instead. This alias will be removed in the next major version. */
  readonly "enemy_location": __DbViewBase["enemyLocation"];
  /** @deprecated Use `growthTimers` instead. This alias will be removed in the next major version. */
  readonly "growth_timers": __DbViewBase["growthTimers"];
  /** @deprecated Use `herdLocation` instead. This alias will be removed in the next major version. */
  readonly "herd_location": __DbViewBase["herdLocation"];
  /** @deprecated Use `playerLocation` instead. This alias will be removed in the next major version. */
  readonly "player_location": __DbViewBase["playerLocation"];
  /** @deprecated Use `playerState` instead. This alias will be removed in the next major version. */
  readonly "player_state": __DbViewBase["playerState"];
  /** @deprecated Use `recipeMeta` instead. This alias will be removed in the next major version. */
  readonly "recipe_meta": __DbViewBase["recipeMeta"];
  /** @deprecated Use `resourceLocation` instead. This alias will be removed in the next major version. */
  readonly "resource_location": __DbViewBase["resourceLocation"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `claimInfo` instead. This alias will be removed in the next major version. */
  readonly "claim_info": __TablesBase["claimInfo"];
  /** @deprecated Use `claimMember` instead. This alias will be removed in the next major version. */
  readonly "claim_member": __TablesBase["claimMember"];
  /** @deprecated Use `claimMeta` instead. This alias will be removed in the next major version. */
  readonly "claim_meta": __TablesBase["claimMeta"];
  /** @deprecated Use `claimSupply` instead. This alias will be removed in the next major version. */
  readonly "claim_supply": __TablesBase["claimSupply"];
  /** @deprecated Use `craftContribution` instead. This alias will be removed in the next major version. */
  readonly "craft_contribution": __TablesBase["craftContribution"];
  /** @deprecated Use `craftMeta` instead. This alias will be removed in the next major version. */
  readonly "craft_meta": __TablesBase["craftMeta"];
  /** @deprecated Use `craftProgress` instead. This alias will be removed in the next major version. */
  readonly "craft_progress": __TablesBase["craftProgress"];
  /** @deprecated Use `enemyLocation` instead. This alias will be removed in the next major version. */
  readonly "enemy_location": __TablesBase["enemyLocation"];
  /** @deprecated Use `growthTimers` instead. This alias will be removed in the next major version. */
  readonly "growth_timers": __TablesBase["growthTimers"];
  /** @deprecated Use `herdLocation` instead. This alias will be removed in the next major version. */
  readonly "herd_location": __TablesBase["herdLocation"];
  /** @deprecated Use `playerLocation` instead. This alias will be removed in the next major version. */
  readonly "player_location": __TablesBase["playerLocation"];
  /** @deprecated Use `playerState` instead. This alias will be removed in the next major version. */
  readonly "player_state": __TablesBase["playerState"];
  /** @deprecated Use `recipeMeta` instead. This alias will be removed in the next major version. */
  readonly "recipe_meta": __TablesBase["recipeMeta"];
  /** @deprecated Use `resourceLocation` instead. This alias will be removed in the next major version. */
  readonly "resource_location": __TablesBase["resourceLocation"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

