// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  effortRequired: __t.i32().name("effort_required"),
  skillId: __t.i32().name("skill_id"),
  expPerProgress: __t.f32().name("exp_per_progress"),
  levelRequired: __t.i32().name("level_required"),
});
