// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  name: __t.string(),
  minChunkX: __t.u16().name("min_chunk_x"),
  minChunkZ: __t.u16().name("min_chunk_z"),
  widthChunks: __t.u16().name("width_chunks"),
  heightChunks: __t.u16().name("height_chunks"),
  initialized: __t.bool(),
  allowPlayers: __t.bool().name("allow_players"),
  allowPlayerSpawns: __t.bool().name("allow_player_spawns"),
});
