// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {type Infer as __Infer, t as __t,} from "spacetimedb";

export const ClaimInfo = __t.object("ClaimInfo", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  bank: __t.bool(),
  marketplace: __t.bool(),
  waystone: __t.bool(),
  research: __t.array(__t.i32()),
  name: __t.string(),
});
export type ClaimInfo = __Infer<typeof ClaimInfo>;

// The tagged union or sum type for the algebraic type `ClaimInfoField`.
export const ClaimInfoField = __t.enum("ClaimInfoField", {
  Name: __t.string(),
  Bank: __t.bool(),
  Marketplace: __t.bool(),
  Waystone: __t.bool(),
  Research: __t.array(__t.i32()),
});
export type ClaimInfoField = __Infer<typeof ClaimInfoField>;

export const ClaimInfoUpdate = __t.object("ClaimInfoUpdate", {
  entityId: __t.u64(),
  get field() {
    return ClaimInfoField;
  },
});
export type ClaimInfoUpdate = __Infer<typeof ClaimInfoUpdate>;

export const ClaimMember = __t.object("ClaimMember", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  claimEntityId: __t.u64(),
  playerEntityId: __t.u64(),
  build: __t.bool(),
  inventory: __t.bool(),
  officer: __t.bool(),
  coOwner: __t.bool(),
  owner: __t.bool(),
});
export type ClaimMember = __Infer<typeof ClaimMember>;

export const ClaimMeta = __t.object("ClaimMeta", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
  buildingDescId: __t.i32(),
});
export type ClaimMeta = __Infer<typeof ClaimMeta>;

export const ClaimOwnerUpdate = __t.object("ClaimOwnerUpdate", {
  claimEntityId: __t.u64(),
  ownerPlayerEntityId: __t.u64(),
});
export type ClaimOwnerUpdate = __Infer<typeof ClaimOwnerUpdate>;

export const ClaimSupply = __t.object("ClaimSupply", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  supplies: __t.i32(),
  numTiles: __t.u32(),
  numTileNeighbors: __t.u32(),
  buildingMaintenance: __t.f32(),
});
export type ClaimSupply = __Infer<typeof ClaimSupply>;

export const CraftContribution = __t.object("CraftContribution", {
  id: __t.u64(),
  craftId: __t.u64(),
  playerId: __t.u64(),
  contribution: __t.i32(),
});
export type CraftContribution = __Infer<typeof CraftContribution>;

export const CraftContributionDelta = __t.object("CraftContributionDelta", {
  craftId: __t.u64(),
  playerId: __t.u64(),
  progressDelta: __t.i32(),
  progressTotal: __t.i32(),
  lastSeen: __t.timestamp(),
});
export type CraftContributionDelta = __Infer<typeof CraftContributionDelta>;

export const CraftExpiry = __t.object("CraftExpiry", {
  craftId: __t.u64(),
  get status() {
    return CraftStatus;
  },
});
export type CraftExpiry = __Infer<typeof CraftExpiry>;

export const CraftMeta = __t.object("CraftMeta", {
  entityId: __t.u64(),
  ownerEntityId: __t.u64(),
  claimEntityId: __t.u64(),
  buildingEntityId: __t.u64(),
  firstSeen: __t.timestamp(),
  recipeId: __t.i32(),
  count: __t.i32(),
  regionId: __t.u8(),
  public: __t.bool(),
  get status() {
    return CraftStatus;
  },
});
export type CraftMeta = __Infer<typeof CraftMeta>;

export const CraftProgress = __t.object("CraftProgress", {
  entityId: __t.u64(),
  lastSeen: __t.timestamp(),
  progress: __t.i32(),
});
export type CraftProgress = __Infer<typeof CraftProgress>;

export const CraftPublicUpdate = __t.object("CraftPublicUpdate", {
  craftId: __t.u64(),
  public: __t.bool(),
});
export type CraftPublicUpdate = __Infer<typeof CraftPublicUpdate>;

// The tagged union or sum type for the algebraic type `CraftStatus`.
export const CraftStatus = __t.enum("CraftStatus", {
  Active: __t.unit(),
  Claimed: __t.unit(),
  Removed: __t.unit(),
});
export type CraftStatus = __Infer<typeof CraftStatus>;

export const CraftUpdate = __t.object("CraftUpdate", {
  entityId: __t.u64(),
  ownerEntityId: __t.u64(),
  claimEntityId: __t.u64(),
  buildingEntityId: __t.u64(),
  firstSeen: __t.timestamp(),
  recipeId: __t.i32(),
  count: __t.i32(),
  regionId: __t.u8(),
  public: __t.bool(),
  progress: __t.i32(),
  lastSeen: __t.timestamp(),
});
export type CraftUpdate = __Infer<typeof CraftUpdate>;

export const EnemyLocation = __t.object("EnemyLocation", {
  entityId: __t.u64(),
  enemyType: __t.i32(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
});
export type EnemyLocation = __Infer<typeof EnemyLocation>;

export const ExpiringCraft = __t.object("ExpiringCraft", {
  craftId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpiringCraft = __Infer<typeof ExpiringCraft>;

export const GrowthTimer = __t.object("GrowthTimer", {
  entityId: __t.u64(),
  resourceId: __t.i32(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
  endTimestamp: __t.timestamp(),
});
export type GrowthTimer = __Infer<typeof GrowthTimer>;

export const GrowthTimerUpdate = __t.object("GrowthTimerUpdate", {
  entityId: __t.u64(),
  endTimestamp: __t.timestamp(),
});
export type GrowthTimerUpdate = __Infer<typeof GrowthTimerUpdate>;

export const HerdLocation = __t.object("HerdLocation", {
  entityId: __t.u64(),
  enemyType: __t.i32(),
  enemyParamsAiDescId: __t.i32(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
});
export type HerdLocation = __Infer<typeof HerdLocation>;

export const MobileMoveUpdate = __t.object("MobileMoveUpdate", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
});
export type MobileMoveUpdate = __Infer<typeof MobileMoveUpdate>;

export const PlayerLocation = __t.object("PlayerLocation", {
  entityId: __t.u64(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
});
export type PlayerLocation = __Infer<typeof PlayerLocation>;

export const PlayerRenameUpdate = __t.object("PlayerRenameUpdate", {
  entityId: __t.u64(),
  name: __t.string(),
});
export type PlayerRenameUpdate = __Infer<typeof PlayerRenameUpdate>;

export const PlayerState = __t.object("PlayerState", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  online: __t.bool(),
  name: __t.string(),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const RecipeMeta = __t.object("RecipeMeta", {
  id: __t.i32(),
  effortRequired: __t.i32(),
  skillId: __t.i32(),
  expPerProgress: __t.f32(),
  levelRequired: __t.i32(),
});
export type RecipeMeta = __Infer<typeof RecipeMeta>;

export const Region = __t.object("Region", {
  id: __t.u8(),
  name: __t.string(),
  minChunkX: __t.u16(),
  minChunkZ: __t.u16(),
  widthChunks: __t.u16(),
  heightChunks: __t.u16(),
  initialized: __t.bool(),
  allowPlayers: __t.bool(),
  allowPlayerSpawns: __t.bool(),
});
export type Region = __Infer<typeof Region>;

export const RelayConfig = __t.object("RelayConfig", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type RelayConfig = __Infer<typeof RelayConfig>;

export const ResourceLocation = __t.object("ResourceLocation", {
  entityId: __t.u64(),
  resourceId: __t.i32(),
  regionId: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
});
export type ResourceLocation = __Infer<typeof ResourceLocation>;

