// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";
import {LoyaltyRuleSpec,} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  payerAccountIdentity: __t.identity().name("payer_account_identity"),
  currency: __t.string(),
  get spec() {
    return LoyaltyRuleSpec;
  },
  bonusRatioNumerator: __t.i64().name("bonus_ratio_numerator"),
  bonusRatioDenominator: __t.i64().name("bonus_ratio_denominator"),
  updatedAt: __t.timestamp().name("updated_at"),
});
