// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  payerAccountIdentity: __t.identity().name("payer_account_identity"),
  payeePlayerId: __t.u64().name("payee_player_id"),
  currency: __t.string(),
  total: __t.i64(),
  totalEffort: __t.i64().name("total_effort"),
  updatedAt: __t.timestamp().name("updated_at"),
});
