// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";
import {DiscordWatchDisplayContent,} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  filterId: __t.string().name("filter_id"),
  channelId: __t.string().name("channel_id"),
  get content() {
    return DiscordWatchDisplayContent;
  },
  style: __t.string(),
  sortField: __t.string().name("sort_field"),
  sortDirection: __t.string().name("sort_direction"),
  limit: __t.u32(),
  stickyMinutes: __t.u32().name("sticky_minutes"),
  refreshIntervalSeconds: __t.u32().name("refresh_interval_seconds"),
  shareCode: __t.option(__t.string()).name("share_code"),
  messageId: __t.option(__t.string()).name("message_id"),
  lastPostedAt: __t.option(__t.timestamp()).name("last_posted_at"),
  lastEditedAt: __t.option(__t.timestamp()).name("last_edited_at"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
