// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default {
  craftId: __t.u64(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  currency: __t.string(),
  assignedByAccountIdentity: __t.identity(),
  private: __t.bool(),
  assignedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
};
