// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {DiscordWatchDisplayContent,} from "./types";

export default {
  id: __t.string(),
  accountIdentity: __t.identity(),
  filterId: __t.string(),
  channelId: __t.string(),
  get content() {
    return DiscordWatchDisplayContent;
  },
  style: __t.string(),
  sortField: __t.string(),
  sortDirection: __t.string(),
  limit: __t.u32(),
  stickyMinutes: __t.u32(),
  refreshIntervalSeconds: __t.u32(),
  shareCode: __t.option(__t.string()),
};
