// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default {
  id: __t.string(),
  accountIdentity: __t.identity(),
  channelId: __t.string(),
  channelName: __t.option(__t.string()),
  defaultMentionType: __t.option(__t.string()),
  defaultMentionId: __t.option(__t.string()),
  defaultMentionName: __t.option(__t.string()),
};
