// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default {
  payerAccountIdentity: __t.identity(),
  payeePlayerId: __t.u64(),
  currency: __t.string(),
  totalEffort: __t.i64(),
  total: __t.i64(),
  paidTotal: __t.i64(),
};
