// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {HistoricalBountyLedgerRow,} from "./types";

export default {
  payerAccountIdentity: __t.identity(),
  get rows() {
    return __t.array(HistoricalBountyLedgerRow);
  },
};
