// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  convertToAccessorMap as __convertToAccessorMap,
  DbConnectionBuilder as __DbConnectionBuilder,
  type DbConnectionConfig as __DbConnectionConfig,
  DbConnectionImpl as __DbConnectionImpl,
  type ErrorContextInterface as __ErrorContextInterface,
  type EventContextInterface as __EventContextInterface,
  makeQueryBuilder as __makeQueryBuilder,
  procedures as __procedures,
  procedureSchema as __procedureSchema,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  reducers as __reducers,
  reducerSchema as __reducerSchema,
  type RemoteModule as __RemoteModule,
  schema as __schema,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
  table as __table,
} from "spacetimedb";

// Import all table schema definitions
import AllAccountRow from "./all_account_table";
import AllBountyRuleRow from "./all_bounty_rule_table";
import AllCraftBountyAssignmentRow from "./all_craft_bounty_assignment_table";
import AllCraftBountyEntitlementRow from "./all_craft_bounty_entitlement_table";
import AllCraftBountyOverrideRow from "./all_craft_bounty_override_table";
import AllCraftFilterWatchRow from "./all_craft_filter_watch_table";
import AllIntegrationLinkRequestRow from "./all_integration_link_request_table";
import AllLinkedIntegrationRow from "./all_linked_integration_table";
import AllLoyaltyRewardRow from "./all_loyalty_reward_table";
import AllPrivateCraftBountyAssignmentRow from "./all_private_craft_bounty_assignment_table";
import AllSavedCraftFilterRow from "./all_saved_craft_filter_table";

// Import all reducer arg schemas
import AssignCraftBountyReducer from "./assign_craft_bounty_reducer";
import BeginIntegrationLinkForExternalReducer from "./begin_integration_link_for_external_reducer";
import BeginIntegrationLinkReducer from "./begin_integration_link_reducer";
import ClaimIntegrationLinkReducer from "./claim_integration_link_reducer";
import ClearCraftBountyReducer from "./clear_craft_bounty_reducer";

// Import all procedure arg schemas
import * as CreateSharedFiltersProcedure from "./create_shared_filters_procedure";
import DeleteBountyRuleReducer from "./delete_bounty_rule_reducer";
import DeleteCraftBountyOverrideReducer from "./delete_craft_bounty_override_reducer";
import DeleteCraftFilterWatchReducer from "./delete_craft_filter_watch_reducer";
import DeleteLoyaltyRewardReducer from "./delete_loyalty_reward_reducer";
import DeleteNotificationReducer from "./delete_notification_reducer";
import DeleteSavedCraftFilterReducer from "./delete_saved_craft_filter_reducer";
import EnsureAccountReducer from "./ensure_account_reducer";
import LinkDiscordViaSpacetimeAuthReducer from "./link_discord_via_spacetime_auth_reducer";
import LinkIntegrationReducer from "./link_integration_reducer";
import MarkAllNotificationsReadReducer from "./mark_all_notifications_read_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import MyAccountRow from "./my_account_table";
import MyBountyPayoutRecordAsPayerRow from "./my_bounty_payout_record_as_payer_table";
import MyBountyRuleRow from "./my_bounty_rule_table";
import MyCraftBountyOverrideRow from "./my_craft_bounty_override_table";
import MyCraftFilterWatchRow from "./my_craft_filter_watch_table";
import MyEntitlementsAsContributorRow from "./my_entitlements_as_contributor_table";
import MyEntitlementsAsPayerRow from "./my_entitlements_as_payer_table";
import MyIntegrationLinkRequestRow from "./my_integration_link_request_table";
import MyLinkedIntegrationRow from "./my_linked_integration_table";
import MyLoyaltyRewardRow from "./my_loyalty_reward_table";
import MyNotificationRow from "./my_notification_table";
import MyPrivateCraftBountyAssignmentRow from "./my_private_craft_bounty_assignment_table";
import MySavedCraftFilterRow from "./my_saved_craft_filter_table";
import NoteIntegrationLinkExternalReducer from "./note_integration_link_external_reducer";
import PostCraftNotificationReducer from "./post_craft_notification_reducer";
import * as ReadSharedFiltersProcedure from "./read_shared_filters_procedure";
import RecordBountyPaymentReducer from "./record_bounty_payment_reducer";
import RegisterServicePrincipalReducer from "./register_service_principal_reducer";
import ReorderBountyRulesReducer from "./reorder_bounty_rules_reducer";
import RevokeServicePrincipalReducer from "./revoke_service_principal_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import UnlinkIntegrationReducer from "./unlink_integration_reducer";
import UpsertBountyRuleReducer from "./upsert_bounty_rule_reducer";
import UpsertCraftBountyEntitlementReducer from "./upsert_craft_bounty_entitlement_reducer";
import UpsertCraftBountyOverrideReducer from "./upsert_craft_bounty_override_reducer";
import UpsertCraftFilterWatchReducer from "./upsert_craft_filter_watch_reducer";
import UpsertLoyaltyRewardReducer from "./upsert_loyalty_reward_reducer";
import UpsertSavedCraftFilterReducer from "./upsert_saved_craft_filter_reducer";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  allAccount: __table({
    name: 'all_account',
    indexes: [
    ],
    constraints: [
    ],
  }, AllAccountRow),
  allBountyRule: __table({
    name: 'all_bounty_rule',
    indexes: [
    ],
    constraints: [
    ],
  }, AllBountyRuleRow),
  allCraftBountyAssignment: __table({
    name: 'all_craft_bounty_assignment',
    indexes: [
    ],
    constraints: [
    ],
  }, AllCraftBountyAssignmentRow),
  allCraftBountyEntitlement: __table({
    name: 'all_craft_bounty_entitlement',
    indexes: [
    ],
    constraints: [
    ],
  }, AllCraftBountyEntitlementRow),
  allCraftBountyOverride: __table({
    name: 'all_craft_bounty_override',
    indexes: [
    ],
    constraints: [
    ],
  }, AllCraftBountyOverrideRow),
  allCraftFilterWatch: __table({
    name: 'all_craft_filter_watch',
    indexes: [
    ],
    constraints: [
    ],
  }, AllCraftFilterWatchRow),
  allIntegrationLinkRequest: __table({
    name: 'all_integration_link_request',
    indexes: [
    ],
    constraints: [
    ],
  }, AllIntegrationLinkRequestRow),
  allLinkedIntegration: __table({
    name: 'all_linked_integration',
    indexes: [
    ],
    constraints: [
    ],
  }, AllLinkedIntegrationRow),
  allLoyaltyReward: __table({
    name: 'all_loyalty_reward',
    indexes: [
    ],
    constraints: [
    ],
  }, AllLoyaltyRewardRow),
  allPrivateCraftBountyAssignment: __table({
    name: 'all_private_craft_bounty_assignment',
    indexes: [
    ],
    constraints: [
    ],
  }, AllPrivateCraftBountyAssignmentRow),
  allSavedCraftFilter: __table({
    name: 'all_saved_craft_filter',
    indexes: [
    ],
    constraints: [
    ],
  }, AllSavedCraftFilterRow),
  myAccount: __table({
    name: 'my_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  myBountyPayoutRecordAsPayer: __table({
    name: 'my_bounty_payout_record_as_payer',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBountyPayoutRecordAsPayerRow),
  myBountyRule: __table({
    name: 'my_bounty_rule',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBountyRuleRow),
  myCraftBountyOverride: __table({
    name: 'my_craft_bounty_override',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCraftBountyOverrideRow),
  myCraftFilterWatch: __table({
    name: 'my_craft_filter_watch',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCraftFilterWatchRow),
  myEntitlementsAsContributor: __table({
    name: 'my_entitlements_as_contributor',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEntitlementsAsContributorRow),
  myEntitlementsAsPayer: __table({
    name: 'my_entitlements_as_payer',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEntitlementsAsPayerRow),
  myIntegrationLinkRequest: __table({
    name: 'my_integration_link_request',
    indexes: [
    ],
    constraints: [
    ],
  }, MyIntegrationLinkRequestRow),
  myLinkedIntegration: __table({
    name: 'my_linked_integration',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLinkedIntegrationRow),
  myLoyaltyReward: __table({
    name: 'my_loyalty_reward',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLoyaltyRewardRow),
  myNotification: __table({
    name: 'my_notification',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationRow),
  myPrivateCraftBountyAssignment: __table({
    name: 'my_private_craft_bounty_assignment',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPrivateCraftBountyAssignmentRow),
  mySavedCraftFilter: __table({
    name: 'my_saved_craft_filter',
    indexes: [
    ],
    constraints: [
    ],
  }, MySavedCraftFilterRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("assign_craft_bounty", AssignCraftBountyReducer),
  __reducerSchema("begin_integration_link", BeginIntegrationLinkReducer),
  __reducerSchema("begin_integration_link_for_external", BeginIntegrationLinkForExternalReducer),
  __reducerSchema("claim_integration_link", ClaimIntegrationLinkReducer),
  __reducerSchema("clear_craft_bounty", ClearCraftBountyReducer),
  __reducerSchema("delete_bounty_rule", DeleteBountyRuleReducer),
  __reducerSchema("delete_craft_bounty_override", DeleteCraftBountyOverrideReducer),
  __reducerSchema("delete_craft_filter_watch", DeleteCraftFilterWatchReducer),
  __reducerSchema("delete_loyalty_reward", DeleteLoyaltyRewardReducer),
  __reducerSchema("delete_notification", DeleteNotificationReducer),
  __reducerSchema("delete_saved_craft_filter", DeleteSavedCraftFilterReducer),
  __reducerSchema("ensure_account", EnsureAccountReducer),
  __reducerSchema("link_discord_via_spacetime_auth", LinkDiscordViaSpacetimeAuthReducer),
  __reducerSchema("link_integration", LinkIntegrationReducer),
  __reducerSchema("mark_all_notifications_read", MarkAllNotificationsReadReducer),
  __reducerSchema("mark_notification_read", MarkNotificationReadReducer),
  __reducerSchema("note_integration_link_external", NoteIntegrationLinkExternalReducer),
  __reducerSchema("post_craft_notification", PostCraftNotificationReducer),
  __reducerSchema("record_bounty_payment", RecordBountyPaymentReducer),
  __reducerSchema("register_service_principal", RegisterServicePrincipalReducer),
  __reducerSchema("reorder_bounty_rules", ReorderBountyRulesReducer),
  __reducerSchema("revoke_service_principal", RevokeServicePrincipalReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("unlink_integration", UnlinkIntegrationReducer),
  __reducerSchema("upsert_bounty_rule", UpsertBountyRuleReducer),
  __reducerSchema("upsert_craft_bounty_entitlement", UpsertCraftBountyEntitlementReducer),
  __reducerSchema("upsert_craft_bounty_override", UpsertCraftBountyOverrideReducer),
  __reducerSchema("upsert_craft_filter_watch", UpsertCraftFilterWatchReducer),
  __reducerSchema("upsert_loyalty_reward", UpsertLoyaltyRewardReducer),
  __reducerSchema("upsert_saved_craft_filter", UpsertSavedCraftFilterReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("create_shared_filters", CreateSharedFiltersProcedure.params, CreateSharedFiltersProcedure.returnType),
  __procedureSchema("read_shared_filters", ReadSharedFiltersProcedure.params, ReadSharedFiltersProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

