// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";
import {BountyRuleValue,} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  priority: __t.i32(),
  filterJson: __t.string().name("filter_json"),
  get value() {
    return BountyRuleValue;
  },
  private: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
