// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  craftId: __t.u64().primaryKey().name("craft_id"),
  accountIdentity: __t.identity().name("account_identity"),
  ratioNumerator: __t.i64().name("ratio_numerator"),
  ratioDenominator: __t.i64().name("ratio_denominator"),
  currency: __t.string(),
  private: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
});
