// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  channelId: __t.string().name("channel_id"),
  channelName: __t.option(__t.string()).name("channel_name"),
  defaultMentionType: __t.option(__t.string()).name("default_mention_type"),
  defaultMentionId: __t.option(__t.string()).name("default_mention_id"),
  defaultMentionName: __t.option(__t.string()).name("default_mention_name"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
