// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  filterId: __t.string().name("filter_id"),
  sinkId: __t.string().name("sink_id"),
  addedTemplate: __t.option(__t.string()).name("added_template"),
  finishedTemplate: __t.option(__t.string()).name("finished_template"),
  removedTemplate: __t.option(__t.string()).name("removed_template"),
  mentionType: __t.option(__t.string()).name("mention_type"),
  mentionId: __t.option(__t.string()).name("mention_id"),
  mentionName: __t.option(__t.string()).name("mention_name"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
