// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  payerAccountIdentity: __t.identity().name("payer_account_identity"),
  payerName: __t.string().name("payer_name"),
  payeePlayerId: __t.u64().name("payee_player_id"),
  currency: __t.string(),
  effortTotal: __t.i64().name("effort_total"),
  earnedTotal: __t.i64().name("earned_total"),
  paidTotal: __t.i64().name("paid_total"),
});
