// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  code: __t.string(),
  provider: __t.string(),
  accountIdentity: __t.option(__t.identity()).name("account_identity"),
  externalId: __t.option(__t.string()).name("external_id"),
  externalHandle: __t.option(__t.string()).name("external_handle"),
  createdAt: __t.timestamp().name("created_at"),
});
