// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  provider: __t.string(),
  externalId: __t.string().name("external_id"),
  externalHandle: __t.option(__t.string()).name("external_handle"),
  linkedAt: __t.timestamp().name("linked_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
});
