// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";
import {NotificationPayload,} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  accountIdentity: __t.identity().name("account_identity"),
  get payload() {
    return NotificationPayload;
  },
  createdAt: __t.timestamp().name("created_at"),
  readAt: __t.option(__t.timestamp()).name("read_at"),
});
