// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {CraftNotificationPayload,} from "./types";

export default {
  accountIdentity: __t.identity(),
  get payload() {
    return CraftNotificationPayload;
  },
};
