// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {type Infer as __Infer, t as __t,} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  issuer: __t.string(),
  subject: __t.string(),
  displayName: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AllAccount = __t.object("AllAccount", {});
export type AllAccount = __Infer<typeof AllAccount>;

export const AllBountyRule = __t.object("AllBountyRule", {});
export type AllBountyRule = __Infer<typeof AllBountyRule>;

export const AllCraftBountyAssignment = __t.object("AllCraftBountyAssignment", {});
export type AllCraftBountyAssignment = __Infer<typeof AllCraftBountyAssignment>;

export const AllCraftBountyEntitlement = __t.object("AllCraftBountyEntitlement", {});
export type AllCraftBountyEntitlement = __Infer<typeof AllCraftBountyEntitlement>;

export const AllCraftBountyOverride = __t.object("AllCraftBountyOverride", {});
export type AllCraftBountyOverride = __Infer<typeof AllCraftBountyOverride>;

export const AllCraftFilterWatch = __t.object("AllCraftFilterWatch", {});
export type AllCraftFilterWatch = __Infer<typeof AllCraftFilterWatch>;

export const AllIntegrationLinkRequest = __t.object("AllIntegrationLinkRequest", {});
export type AllIntegrationLinkRequest = __Infer<typeof AllIntegrationLinkRequest>;

export const AllLinkedIntegration = __t.object("AllLinkedIntegration", {});
export type AllLinkedIntegration = __Infer<typeof AllLinkedIntegration>;

export const AllLoyaltyReward = __t.object("AllLoyaltyReward", {});
export type AllLoyaltyReward = __Infer<typeof AllLoyaltyReward>;

export const AllPrivateCraftBountyAssignment = __t.object("AllPrivateCraftBountyAssignment", {});
export type AllPrivateCraftBountyAssignment = __Infer<typeof AllPrivateCraftBountyAssignment>;

export const AllSavedCraftFilter = __t.object("AllSavedCraftFilter", {});
export type AllSavedCraftFilter = __Infer<typeof AllSavedCraftFilter>;

export const BountyEntitlementTotal = __t.object("BountyEntitlementTotal", {
  id: __t.u64(),
  payerAccountIdentity: __t.identity(),
  payeePlayerId: __t.u64(),
  currency: __t.string(),
  total: __t.i64(),
  totalEffort: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type BountyEntitlementTotal = __Infer<typeof BountyEntitlementTotal>;

export const BountyPayoutRecord = __t.object("BountyPayoutRecord", {
  id: __t.u64(),
  payerAccountIdentity: __t.identity(),
  payeePlayerId: __t.u64(),
  currency: __t.string(),
  paidTotal: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type BountyPayoutRecord = __Infer<typeof BountyPayoutRecord>;

export const BountyRule = __t.object("BountyRule", {
  id: __t.string(),
  accountIdentity: __t.identity(),
  priority: __t.i32(),
  filterJson: __t.string(),
  get value() {
    return BountyRuleValue;
  },
  private: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type BountyRule = __Infer<typeof BountyRule>;

// The tagged union or sum type for the algebraic type `BountyRuleValue`.
export const BountyRuleValue = __t.enum("BountyRuleValue", {
  get Flat() {
    return FlatBountyValue;
  },
  get Grid() {
    return GridBountyValue;
  },
});
export type BountyRuleValue = __Infer<typeof BountyRuleValue>;

export const ContributorEntitlementRow = __t.object("ContributorEntitlementRow", {
  id: __t.string(),
  payerAccountIdentity: __t.identity(),
  payerName: __t.string(),
  payeePlayerId: __t.u64(),
  currency: __t.string(),
  effortTotal: __t.i64(),
  earnedTotal: __t.i64(),
  paidTotal: __t.i64(),
});
export type ContributorEntitlementRow = __Infer<typeof ContributorEntitlementRow>;

export const CraftBountyAssignment = __t.object("CraftBountyAssignment", {
  craftId: __t.u64(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  currency: __t.string(),
  assignedByAccountIdentity: __t.identity(),
  assignedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CraftBountyAssignment = __Infer<typeof CraftBountyAssignment>;

export const CraftBountyEntitlement = __t.object("CraftBountyEntitlement", {
  id: __t.u64(),
  craftId: __t.u64(),
  playerId: __t.u64(),
  currency: __t.string(),
  lastAssignedEffort: __t.i64(),
  entitledTotal: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type CraftBountyEntitlement = __Infer<typeof CraftBountyEntitlement>;

export const CraftBountyOverride = __t.object("CraftBountyOverride", {
  craftId: __t.u64(),
  accountIdentity: __t.identity(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  currency: __t.string(),
  private: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type CraftBountyOverride = __Infer<typeof CraftBountyOverride>;

export const CraftFilterWatch = __t.object("CraftFilterWatch", {
  filterId: __t.string(),
  accountIdentity: __t.identity(),
  added: __t.bool(),
  finished: __t.bool(),
  removed: __t.bool(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type CraftFilterWatch = __Infer<typeof CraftFilterWatch>;

export const CraftNotificationPayload = __t.object("CraftNotificationPayload", {
  watchId: __t.string(),
  filterName: __t.string(),
  eventKind: __t.string(),
  craftId: __t.string(),
  recipeId: __t.i32(),
  regionName: __t.string(),
  claimName: __t.option(__t.string()),
  ownerName: __t.option(__t.string()),
});
export type CraftNotificationPayload = __Infer<typeof CraftNotificationPayload>;

export const CraftPrivateBountyAssignment = __t.object("CraftPrivateBountyAssignment", {
  craftId: __t.u64(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  currency: __t.string(),
  assignedByAccountIdentity: __t.identity(),
  assignedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CraftPrivateBountyAssignment = __Infer<typeof CraftPrivateBountyAssignment>;

export const CreateSharedFiltersResult = __t.object("CreateSharedFiltersResult", {
  code: __t.string(),
});
export type CreateSharedFiltersResult = __Infer<typeof CreateSharedFiltersResult>;

export const FlatBountyValue = __t.object("FlatBountyValue", {
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  currency: __t.string(),
});
export type FlatBountyValue = __Infer<typeof FlatBountyValue>;

export const GridBountyValue = __t.object("GridBountyValue", {
  get cells() {
    return __t.array(GridCell);
  },
  currency: __t.string(),
});
export type GridBountyValue = __Infer<typeof GridBountyValue>;

export const GridCell = __t.object("GridCell", {
  skillId: __t.u32(),
  tier: __t.u32(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
});
export type GridCell = __Infer<typeof GridCell>;

export const IntegrationLinkRequest = __t.object("IntegrationLinkRequest", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  code: __t.string(),
  provider: __t.string(),
  accountIdentity: __t.option(__t.identity()),
  externalId: __t.option(__t.string()),
  externalHandle: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type IntegrationLinkRequest = __Infer<typeof IntegrationLinkRequest>;

export const LinkedIntegration = __t.object("LinkedIntegration", {
  id: __t.u64(),
  accountIdentity: __t.identity(),
  provider: __t.string(),
  externalId: __t.string(),
  externalHandle: __t.option(__t.string()),
  linkedAt: __t.timestamp(),
  revokedAt: __t.option(__t.timestamp()),
});
export type LinkedIntegration = __Infer<typeof LinkedIntegration>;

export const LoyaltyReward = __t.object("LoyaltyReward", {
  id: __t.u64(),
  payerAccountIdentity: __t.identity(),
  payeePlayerId: __t.u64(),
  currency: __t.string(),
  ratioNumerator: __t.i64(),
  ratioDenominator: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type LoyaltyReward = __Infer<typeof LoyaltyReward>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyBountyPayoutRecordAsPayer = __t.object("MyBountyPayoutRecordAsPayer", {});
export type MyBountyPayoutRecordAsPayer = __Infer<typeof MyBountyPayoutRecordAsPayer>;

export const MyBountyRule = __t.object("MyBountyRule", {});
export type MyBountyRule = __Infer<typeof MyBountyRule>;

export const MyCraftBountyOverride = __t.object("MyCraftBountyOverride", {});
export type MyCraftBountyOverride = __Infer<typeof MyCraftBountyOverride>;

export const MyCraftFilterWatch = __t.object("MyCraftFilterWatch", {});
export type MyCraftFilterWatch = __Infer<typeof MyCraftFilterWatch>;

export const MyEntitlementsAsContributor = __t.object("MyEntitlementsAsContributor", {});
export type MyEntitlementsAsContributor = __Infer<typeof MyEntitlementsAsContributor>;

export const MyEntitlementsAsPayer = __t.object("MyEntitlementsAsPayer", {});
export type MyEntitlementsAsPayer = __Infer<typeof MyEntitlementsAsPayer>;

export const MyIntegrationLinkRequest = __t.object("MyIntegrationLinkRequest", {});
export type MyIntegrationLinkRequest = __Infer<typeof MyIntegrationLinkRequest>;

export const MyLinkedIntegration = __t.object("MyLinkedIntegration", {});
export type MyLinkedIntegration = __Infer<typeof MyLinkedIntegration>;

export const MyLoyaltyReward = __t.object("MyLoyaltyReward", {});
export type MyLoyaltyReward = __Infer<typeof MyLoyaltyReward>;

export const MyNotification = __t.object("MyNotification", {});
export type MyNotification = __Infer<typeof MyNotification>;

export const MyPrivateCraftBountyAssignment = __t.object("MyPrivateCraftBountyAssignment", {});
export type MyPrivateCraftBountyAssignment = __Infer<typeof MyPrivateCraftBountyAssignment>;

export const MySavedCraftFilter = __t.object("MySavedCraftFilter", {});
export type MySavedCraftFilter = __Infer<typeof MySavedCraftFilter>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  accountIdentity: __t.identity(),
  get payload() {
    return NotificationPayload;
  },
  createdAt: __t.timestamp(),
  readAt: __t.option(__t.timestamp()),
});
export type Notification = __Infer<typeof Notification>;

// The tagged union or sum type for the algebraic type `NotificationPayload`.
export const NotificationPayload = __t.enum("NotificationPayload", {
  get Craft() {
    return CraftNotificationPayload;
  },
});
export type NotificationPayload = __Infer<typeof NotificationPayload>;

export const PayerEntitlementRow = __t.object("PayerEntitlementRow", {
  id: __t.string(),
  payeePlayerId: __t.u64(),
  payeeAccountIdentity: __t.option(__t.identity()),
  payeeName: __t.option(__t.string()),
  currency: __t.string(),
  effortTotal: __t.i64(),
  earnedTotal: __t.i64(),
  paidTotal: __t.i64(),
});
export type PayerEntitlementRow = __Infer<typeof PayerEntitlementRow>;

export const ReadSharedFiltersResult = __t.object("ReadSharedFiltersResult", {
  get filters() {
    return __t.array(SharedFilterRow);
  },
});
export type ReadSharedFiltersResult = __Infer<typeof ReadSharedFiltersResult>;

export const SavedCraftFilter = __t.object("SavedCraftFilter", {
  id: __t.string(),
  accountIdentity: __t.identity(),
  name: __t.string(),
  filterJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type SavedCraftFilter = __Infer<typeof SavedCraftFilter>;

export const ServicePrincipal = __t.object("ServicePrincipal", {
  identity: __t.identity(),
  label: __t.string(),
  grantedAt: __t.timestamp(),
});
export type ServicePrincipal = __Infer<typeof ServicePrincipal>;

export const SharedFilter = __t.object("SharedFilter", {
  code: __t.string(),
  accountIdentity: __t.identity(),
  filterIds: __t.array(__t.string()),
  createdAt: __t.timestamp(),
});
export type SharedFilter = __Infer<typeof SharedFilter>;

export const SharedFilterRow = __t.object("SharedFilterRow", {
  name: __t.string(),
  filterJson: __t.string(),
});
export type SharedFilterRow = __Infer<typeof SharedFilterRow>;

