// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {LoyaltyRuleSpec,} from "./types";

export default {
  id: __t.option(__t.u64()),
  currency: __t.string(),
  get spec() {
    return LoyaltyRuleSpec;
  },
  bonusRatioNumerator: __t.i64(),
  bonusRatioDenominator: __t.i64(),
  updatedAt: __t.timestamp(),
};
