// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {NotifySinkRef,} from "./types";

export default {
  id: __t.string(),
  filterId: __t.string(),
  get sink() {
    return NotifySinkRef;
  },
  added: __t.bool(),
  finished: __t.bool(),
  removed: __t.bool(),
  updatedAt: __t.timestamp(),
};
