// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

import {BountyRuleValue,} from "./types";

export default {
  id: __t.string(),
  filterJson: __t.string(),
  get value() {
    return BountyRuleValue;
  },
  priority: __t.i32(),
  private: __t.bool(),
  updatedAt: __t.timestamp(),
};
