// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {t as __t,} from "spacetimedb";

export default {
  craftId: __t.u64(),
  playerId: __t.u64(),
  currency: __t.string(),
  lastAssignedEffort: __t.i64(),
  entitledTotal: __t.i64(),
  updatedAt: __t.timestamp(),
};
