// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.0 (commit b3547448cf06d65c5133e884c9a24f126f92eb12).

/* eslint-disable */
/* tslint:disable */
import {
  convertToAccessorMap as __convertToAccessorMap,
  DbConnectionBuilder as __DbConnectionBuilder,
  type DbConnectionConfig as __DbConnectionConfig,
  DbConnectionImpl as __DbConnectionImpl,
  type ErrorContextInterface as __ErrorContextInterface,
  type EventContextInterface as __EventContextInterface,
  makeQueryBuilder as __makeQueryBuilder,
  procedures as __procedures,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  reducers as __reducers,
  type RemoteModule as __RemoteModule,
  schema as __schema,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
  table as __table,
} from "spacetimedb";

// Import all reducer arg schemas
// Import all procedure arg schemas
// Import all table schema definitions
import EnemyLocationRow from "./enemy_location_table";
import GrowthTimersRow from "./growth_timers_table";
import PlayerLocationRow from "./player_location_table";
import PlayerStateRow from "./player_state_table";
import ResourceLocationRow from "./resource_location_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  enemy_location: __table({
    name: 'enemy_location',
    indexes: [
      { accessor: 'by_enemy_type', name: 'enemy_location_enemy_type_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
      ] },
      { accessor: 'by_enemy_type_and_region', name: 'enemy_location_enemy_type_region_id_idx_btree', algorithm: 'btree', columns: [
        'enemyType',
        'regionId',
      ] },
      { accessor: 'entity_id', name: 'enemy_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'enemy_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'enemy_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EnemyLocationRow),
  growth_timers: __table({
    name: 'growth_timers',
    indexes: [
      { accessor: 'entity_id', name: 'growth_timers_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'growth_timers_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'growth_timers_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, GrowthTimersRow),
  player_location: __table({
    name: 'player_location',
    indexes: [
      { accessor: 'entity_id', name: 'player_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'player_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'player_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerLocationRow),
  player_state: __table({
    name: 'player_state',
    indexes: [
      { accessor: 'entity_id', name: 'player_state_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'player_state_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'player_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerStateRow),
  resource_location: __table({
    name: 'resource_location',
    indexes: [
      { accessor: 'entity_id', name: 'resource_location_entity_id_idx_hash', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'by_region', name: 'resource_location_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { accessor: 'by_resource', name: 'resource_location_resource_id_idx_btree', algorithm: 'btree', columns: [
        'resourceId',
      ] },
      { accessor: 'by_resource_and_region', name: 'resource_location_resource_id_region_id_idx_btree', algorithm: 'btree', columns: [
        'resourceId',
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'resource_location_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ResourceLocationRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

