// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {type Infer as __Infer, t as __t,} from "spacetimedb";

export const EnemyLocation = __t.object("EnemyLocation", {
  entityId: __t.u64(),
  enemyType: __t.i32(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
});
export type EnemyLocation = __Infer<typeof EnemyLocation>;

export const GrowthTimer = __t.object("GrowthTimer", {
  entityId: __t.u64(),
  resourceId: __t.i32(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
  endTimestamp: __t.timestamp(),
});
export type GrowthTimer = __Infer<typeof GrowthTimer>;

export const PlayerLocation = __t.object("PlayerLocation", {
  entityId: __t.u64(),
  x: __t.i32(),
  z: __t.i32(),
  regionId: __t.u8(),
});
export type PlayerLocation = __Infer<typeof PlayerLocation>;

export const PlayerState = __t.object("PlayerState", {
  entityId: __t.u64(),
  regionId: __t.u8(),
  online: __t.bool(),
  name: __t.string(),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const ResourceLocation = __t.object("ResourceLocation", {
  entityId: __t.u64(),
  resourceId: __t.i32(),
  regionId: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
});
export type ResourceLocation = __Infer<typeof ResourceLocation>;

